name = "ClassicCraft+"
author = "btwonion"
version = "4.3.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "182d90d18f02cad9bdc46a95a7da87830fa5b687fdbaec7673f8a0f563a95687"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"
