name = "onion SMP"
author = "btwonion"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "38f5b08bc14072fa1e797cdca3c8267922dd04a02347a6166470ceb40e0ab9b3"

[versions]
fabric = "0.14.21"
minecraft = "1.20"
