name = "ClassicCraft+"
author = "btwonion"
version = "4.3.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ddef3c0a8774fa3b1c6369e0354177e6e2df93b562fc8f427e1351fc0d890f8c"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"
