name = "ClassicCraft+"
author = "btwonion"
version = "4.3.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "12c91302081f20bb0aaaefbbe11f0aa44e6c97c5389ab6bfa2064aa749fcd456"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"
