name = "ClassicCraft+"
author = "btwonion"
version = "4.4.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3d8e051b26974ad621d3ac1dfb4950fd4ea52323ceb2f91a859cbb81e0296d16"

[versions]
fabric = "0.18.2"
minecraft = "1.21.11"
