name = "ClassicCraft+"
author = "btwonion"
version = "4.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e00ab1b58f81c9a628981ac6d8f44b481429efe12b2bcbb64fa4020a47eaf627"

[versions]
fabric = "0.18.2"
minecraft = "1.21.11"
