name = "ClassicCraft+"
author = "btwonion"
version = "4.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f5d39f9e3df42505fc3eee190c8fd7f1497fa12adae6fba949e0263fccdafaf0"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"
