name = "onion SMP"
author = "btwonion"
version = "1.0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1aa830d59e20c7a06236a08f6926eb4176df423181b3638bc9916f465afb4e6a"

[versions]
fabric = "0.14.19"
minecraft = "1.19.4"
