name = "onion SMP"
author = "btwonion"
version = "2.9.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bc345d4e4e62bf096f189f009eb01c81d9f7e3b038eebb7a72398c8af1b41188"

[versions]
fabric = "0.14.21"
minecraft = "1.20"
