name = "ClassicCraft+"
author = "btwonion"
version = "4.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3e30e965777cb0f6ecd0ae323f1bb31a0eee47e8de9340cdb5f4f44bb508adf1"

[versions]
fabric = "0.18.2"
minecraft = "1.21.11"
