name = "ClassicCraft+"
author = "btwonion"
version = "4.3.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "118825075600147fbb7adac40901eed95d3ca65d84943c2d6f05bd834a959bca"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"
