name = "ClassicCraft+"
author = "btwonion"
version = "4.3.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0f2bdff74ed18a8f6ba4ee7d81c7f3ef8f97585687c535b76559d043e34a835d"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"
