name = "ClassicCraft+"
author = "btwonion"
version = "4.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1e7d72c38b1b48b61b443f613549ad944477d8aa10e4b07b11dc190ef8d66ad3"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
