name = "ClassicCraft+"
author = "btwonion"
version = "4.3.16"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c252eee1e4bd124de75daf51b364b2324e711ed0b36f54947ff4bfa622b9816c"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"
