name = "ClassicCraft+"
author = "btwonion"
version = "4.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fae75932b3d73fbd6057288f8e3cb5a1b632ae60689d0bbb75c87a5666e6c19e"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"

[options]
datapack-folder = "datapacks"
