name = "ClassicCraft+"
author = "btwonion"
version = "4.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cfaa8dfe566b6f44e338f721d51d8d95e3e8439ed2295a4dbf768ad81a75024a"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"
