name = "ClassicCraft+"
author = "btwonion"
version = "4.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "381cf9d4fb8e0bb24c01ede48d01e8c854dbb111564d987dc222963cceae23d5"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"
