name = "ClassicCraft+"
author = "btwonion"
version = "4.3.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e68bc807620d4fc001a41805599ece0ea1e635d224897ebd0573c2c53d1d053f"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"
