name = "ClassicCraft+"
author = "btwonion"
version = "4.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e2c6bc20b0d93016fe6528a15b4201ad4afa686a6da0924bdad81bc22147346e"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"
