name = "ClassicCraft+"
author = "btwonion"
version = "4.3.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4b584ab46e2368f19e6fbda1791877440b3fa05432f65c341962e5e141ab381a"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"
