name = "ClassicCraft+"
author = "btwonion"
version = "4.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "788be01ff4ed4abac1bf48b9682aaf8f7653e5b10d59add93388228efebf3a95"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"
