name = "onion SMP"
author = "btwonion"
version = "1.0.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7e9f3cefd7acc9f05842a1e3d7f87e501af0858c5a770a4d6c14eb932a69dd61"

[versions]
fabric = "0.14.19"
minecraft = "1.19.4"
