name = "ClassicCraft+"
author = "btwonion"
version = "4.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dcb523d4d590a1cc3d149891bc5566899c775f647b65f918b9f760076b3cc294"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"
