name = "onion SMP"
author = "btwonion"
version = "1.0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ee3df34ea715d5b7bbc947e6ba04a450aa21419ea85d1dcea9b476d976f6160b"

[versions]
fabric = "0.14.19"
minecraft = "1.19.4"
