name = "onion SMP"
author = "btwonion"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9a54ea637c6388f081aedc38a2f7fca21c33a753c05aaca2d7e363fea4ac8d94"

[versions]
fabric = "0.14.19"
minecraft = "1.19.4"
