name = "ClassicCraft+"
author = "btwonion"
version = "4.3.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5db4ae3ec8ff8a94438f5dc7c91f221be4d12349623d078ce7f0c32b443285aa"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"
